version: '3.3'

services:
  backend:
    image: ghcr.io/bardolia243/backend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000

  frontend:
    image: ghcr.io/bardolia243/frontend:latest
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - API_URL=http://backend:3000
