version: '3.8'

services:
  frontend:
    image: ghcr.io/bardolia243/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: ghcr.io/bardolia243/backend:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
